name: parallax_ship_track
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  # Flutter widgets implementing the current iOS design language(default dependency)
  cupertino_icons: ^1.0.6
  # easy to integrate blocs and cubits into Flutter
  flutter_bloc: ^8.1.5
  # automatically persists and restores bloc and cubit states
  hydrated_bloc: ^9.1.5
  # exposes custom event transformers
  bloc_concurrency: ^0.2.5
  # Service locator
  get_it: ^7.6.0
  # Value equality
  equatable: ^2.0.5
  # Functional programming thingies
  dartz: ^0.10.1
  # Local cache
  shared_preferences: ^2.2.0
  # Generating copyWith extensions for classes
  copy_with_extension: ^5.0.3
  # A collection of utilities to transform and manipulate streams.
  stream_transform: ^2.1.0
  # Easy and Fast internationalizing and localization your Flutter Apps
  easy_localization: ^3.0.5
  # Flutter plugin for Firebase Core, enabling connecting to multiple Firebase apps.
  firebase_core: ^2.25.4
  # Flutter plugin for Firebase Auth, enabling authentication using passwords, phone numbers and identity providers like Google, Facebook and Twitter.
  firebase_auth: ^4.17.9
  # Flutter plugin for Firebase Database, a cloud-hosted NoSQL database with realtime data syncing across Android and iOS clients, and offline access.
  firebase_database: ^10.4.10
  # Flutter plugin for Firebase Cloud Messaging, a cross-platform messaging solution that lets you reliably deliver messages on Android and iOS.
  firebase_messaging: ^14.7.20
  # Flutter plugin for Firebase Cloud Storage, a powerful, simple, and cost-effective object storage service for Android and iOS.
  firebase_storage: ^11.6.11
  # simplify form representation and validation in a generic way.
  formz: ^0.7.0
  # finding commonly used locations on the filesystem
  path_provider: ^2.1.0
  # check for an Active Internet connection
  internet_connection_checker: ^1.0.0+1
  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl: ^0.18.1
  # A powerful HTTP networking package for Dart/Flutter
  dio: ^5.4.1
  # Annotations for freezed
  freezed_annotation: ^2.4.1
  # adapting screen and font size.Let your UI display a reasonable layout on different screen sizes
  flutter_screenutil: ^5.8.4
  # automatically resizes text to fit perfectly within its bounds
  auto_size_text: ^3.0.0
  # to show images from the internet and keep them in the cache directory
  cached_network_image: ^3.3.0
  # A clean and lightweight loading widget for Flutter, Easy to use without context
  flutter_easyloading: ^3.0.5
  # provides an easy way to add shimmer effect in Flutter project
  shimmer: ^3.0.0
  # TextScroll Flutter widget adds text auto-scrolling functionality
  text_scroll: ^0.2.0
  # Flutter plugin for launching a URL. Supports web, phone, SMS, and email schemes
  url_launcher: ^6.2.5
  # A simple widget to display image in a full-screen, swipe it to dismiss, pinch & zoom
  insta_image_viewer: ^1.0.2
  # Customize Flutter's default white native splash screen with background color and splash image.
  flutter_native_splash: ^2.4.0
  # Draw SVG files using Flutter
  flutter_svg: ^2.0.9
  # A powerful & easy to use timeline package for Flutter. All UI components in this package are separate widgets.
  timelines: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # The "flutter_lints" package below contains a set of recommended lints to encourage good coding practices.
  flutter_lints: ^4.0.0
  copy_with_extension_gen: ^5.0.3
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  background_image: "assets/images/splash.png"

  android_12:
    image: "assets/images/app_icon.png"
    color: "#ffffff"
    icon_background_color: "#000000"

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is included with your application
  uses-material-design: true

  # To add assets to your application, add an assets section:
  assets:
    - assets/
    - assets/svg/
    - assets/images/
    - assets/translations/

  # To add custom fonts to your application, add a fonts section here, in this "flutter" section. Each entry in this list should have a
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.ttf
        - asset: assets/fonts/inter/Inter-Bold.ttf
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
        - asset: assets/fonts/inter/Inter-Light.ttf
        - asset: assets/fonts/inter/Inter-Medium.ttf
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
        - asset: assets/fonts/inter/Inter-Thin.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
        - asset: assets/fonts/montserrat/Montserrat-ThinItalic.ttf
